# заменить значения наименованиями колонок из своего датасета
rename:
  send_ts: send_ts_gen # точный момент отправки в datetime
  accept_bank: accept_bank_gen # акцепт банка
  accept_user: accept_user_gen # акцепт клиента
  client_id: client_id_gen # id

features:
  categorical: [country] # список всех категориальных признаков
  numeric: [age, app_intensity] # # список всех числовых признаков признаков
  time:
    all_generated: [hour, dow, day, hour_sin, hour_cos, dow_sin, dow_cos,
                    day_sin, day_cos,  is_weekend] # не менять